/**
 * Configuração dos upgrades da loja (ganho exponencial por ata).
 * Cada tipo desbloqueia quando lifetimeSelos >= unlockAtLifetimeSelos.
 */
import type { UpgradeDefinition } from './types'

export const UPGRADE_DEFINITIONS: UpgradeDefinition[] = [
  { id: 'caneta', name: 'Caneta', description: '+2% por unidade (exponencial)', lore: 'A ferramenta que dá o primeiro selo. Cada traço conta.', icon: 'caneta', unlockAtLifetimeSelos: 0, baseCost: 10, costMultiplier: 1.15, selosPerAtaPerUnit: 0.02 },
  { id: 'bloco_notas', name: 'Bloco de notas', description: '+3% por unidade (exponencial)', lore: 'Onde as ideias da reunião ganham forma antes de virar ata.', icon: 'bloco_notas', unlockAtLifetimeSelos: 0, baseCost: 50, costMultiplier: 1.15, selosPerAtaPerUnit: 0.03 },
  { id: 'grampeador', name: 'Grampeador', description: '+4% por unidade (exponencial)', lore: 'Mantém as folhas no lugar. Simples, mas essencial.', icon: 'grampeador', unlockAtLifetimeSelos: 0, baseCost: 200, costMultiplier: 1.15, selosPerAtaPerUnit: 0.04 },
  { id: 'organizador_mesa', name: 'Organizador de mesa', description: '+5% por unidade (exponencial)', lore: 'Cada gaveta guarda um projeto. Nada se perde.', icon: 'organizador_mesa', unlockAtLifetimeSelos: 0, baseCost: 500, costMultiplier: 1.15, selosPerAtaPerUnit: 0.05 },
  { id: 'gaveta', name: 'Gaveta', description: '+6% por unidade (exponencial)', lore: 'O primeiro refúgio das atas antes do arquivo definitivo.', icon: 'gaveta', unlockAtLifetimeSelos: 100, baseCost: 1200, costMultiplier: 1.15, selosPerAtaPerUnit: 0.06 },
  { id: 'pasta_arquivo', name: 'Pasta de arquivo', description: '+8% por unidade (exponencial)', lore: 'Uma pasta por reunião. Ordem que acalma.', icon: 'pasta_arquivo', unlockAtLifetimeSelos: 500, baseCost: 3000, costMultiplier: 1.15, selosPerAtaPerUnit: 0.08 },
  { id: 'arquivo_suspenso', name: 'Arquivo suspenso', description: '+10% por unidade (exponencial)', lore: 'Quem nunca sonhou com um arquivo suspenso em casa?', icon: 'arquivo_suspenso', unlockAtLifetimeSelos: 1500, baseCost: 7500, costMultiplier: 1.15, selosPerAtaPerUnit: 0.10 },
  { id: 'armario_aco', name: 'Armário de aço', description: '+12% por unidade (exponencial)', lore: 'A prova de tempo e de esquecimento. O clássico dos escritórios.', icon: 'armario_aco', unlockAtLifetimeSelos: 5000, baseCost: 18000, costMultiplier: 1.15, selosPerAtaPerUnit: 0.12 },
  { id: 'sala_arquivo', name: 'Sala de arquivo', description: '+15% por unidade (exponencial)', lore: 'Um cômodo inteiro dedicado à memória da organização.', icon: 'sala_arquivo', unlockAtLifetimeSelos: 15000, baseCost: 44000, costMultiplier: 1.15, selosPerAtaPerUnit: 0.15 },
  { id: 'biblioteca_atas', name: 'Biblioteca de atas', description: '+18% por unidade (exponencial)', lore: 'Onde cada ata vira uma obra de referência.', icon: 'biblioteca_atas', unlockAtLifetimeSelos: 40000, baseCost: 100000, costMultiplier: 1.15, selosPerAtaPerUnit: 0.18 },
  { id: 'centro_documentacao', name: 'Centro de documentação', description: '+22% por unidade (exponencial)', lore: 'O coração documental da empresa. Tudo passa por aqui.', icon: 'centro_documentacao', unlockAtLifetimeSelos: 100000, baseCost: 250000, costMultiplier: 1.15, selosPerAtaPerUnit: 0.22 },
  { id: 'microfilme', name: 'Microfilme', description: '+26% por unidade (exponencial)', lore: 'Tecnologia do passado que ainda guarda o futuro.', icon: 'microfilme', unlockAtLifetimeSelos: 250000, baseCost: 600000, costMultiplier: 1.15, selosPerAtaPerUnit: 0.26 },
  { id: 'servidor_documentos', name: 'Servidor de documentos', description: '+30% por unidade (exponencial)', lore: 'O arquivo que nunca dorme e está em todo lugar.', icon: 'servidor_documentos', unlockAtLifetimeSelos: 600000, baseCost: 1.4e6, costMultiplier: 1.15, selosPerAtaPerUnit: 0.30 },
  { id: 'nuvem_corporativa', name: 'Nuvem corporativa', description: '+35% por unidade (exponencial)', lore: 'Onde as atas vivem entre o céu e o backup.', icon: 'nuvem_corporativa', unlockAtLifetimeSelos: 1.5e6, baseCost: 3.3e6, costMultiplier: 1.15, selosPerAtaPerUnit: 0.35 },
  { id: 'gestao_documental', name: 'Sistema de gestão documental', description: '+40% por unidade (exponencial)', lore: 'Não é só guardar: é classificar, recuperar e decidir.', icon: 'gestao_documental', unlockAtLifetimeSelos: 4e6, baseCost: 8e6, costMultiplier: 1.15, selosPerAtaPerUnit: 0.40 },
  { id: 'arquivo_nacional', name: 'Arquivo nacional', description: '+48% por unidade (exponencial)', lore: 'Patrimônio de um povo. Suas atas em boa companhia.', icon: 'arquivo_nacional', unlockAtLifetimeSelos: 12e6, baseCost: 2e7, costMultiplier: 1.15, selosPerAtaPerUnit: 0.48 },
  { id: 'memoria_institucional', name: 'Memória institucional', description: '+55% por unidade (exponencial)', lore: 'O que a organização lembra define o que ela é.', icon: 'memoria_institucional', unlockAtLifetimeSelos: 30e6, baseCost: 5e7, costMultiplier: 1.15, selosPerAtaPerUnit: 0.55 },
  { id: 'repositorio_digital', name: 'Repositório digital', description: '+65% por unidade (exponencial)', lore: 'Infinito, pesquisável e à prova de traças.', icon: 'repositorio_digital', unlockAtLifetimeSelos: 80e6, baseCost: 1.2e8, costMultiplier: 1.15, selosPerAtaPerUnit: 0.65 },
  { id: 'camara_permanente', name: 'Câmara de arquivo permanente', description: '+80% por unidade (exponencial)', lore: 'Onde os papéis ganham vida eterna e temperatura controlada.', icon: 'camara_permanente', unlockAtLifetimeSelos: 200e6, baseCost: 3e8, costMultiplier: 1.15, selosPerAtaPerUnit: 0.80 },
  { id: 'patrimonio_documental', name: 'Patrimônio documental', description: '+100% por unidade (exponencial)', lore: 'O topo. Quem chega aqui já virou lenda do arquivamento.', icon: 'patrimonio_documental', unlockAtLifetimeSelos: 500e6, baseCost: 7.5e8, costMultiplier: 1.15, selosPerAtaPerUnit: 1.00 },
]
