import { describe, expect, it } from 'vitest'
import { sanitizeHtml, stripHtml } from './htmlSanitize'

describe('htmlSanitize', () => {
  it('removes scripts and preserves allowed inline formatting', () => {
    const input = '<p>Olá<script>alert(1)</script><span style="color: #007E7A; position: absolute;">mundo</span></p>'
    const out = sanitizeHtml(input)

    expect(out).not.toContain('<script>')
    expect(out).toContain('<p>Olá')
    expect(out).toContain('<span style="color: #007E7A">mundo</span>')
  })

  it('sanitizes img tags allowing only safe data urls and alt text', () => {
    const safeImg = '<img src="data:image/png;base64,aGVsbG8=" alt="imagem &quot;ok&quot;\nquebra" />'
    const unsafeImg = '<img src="javascript:alert(1)" onerror="alert(2)" alt="x" />'

    const safeOut = sanitizeHtml(safeImg)
    expect(safeOut).toContain('<img src="data:image/png;base64,aGVsbG8="')
    expect(safeOut).toContain('alt="imagem  ok  quebra"')
    expect(sanitizeHtml(unsafeImg)).toBe('')
  })

  it('converts unsupported block tags into line breaks to preserve layout', () => {
    const input = '<div>linha 1</div><div>linha 2</div>'
    const out = sanitizeHtml(input)

    expect(out).toContain('linha 1')
    expect(out).toContain('linha 2')
    expect(out).toContain('<br/>')
  })

  it('normalizes repeated break tags generated by nested blocks', () => {
    const input = '<div><div>abc</div></div>'
    const out = sanitizeHtml(input)

    expect(out).toBe('<br/>abc<br/>')
  })
})

describe('stripHtml', () => {
  it('extracts plain text for search/filter use cases', () => {
    const input = '<p><b>Ação</b> <i>pendente</i> até <span style="color:red">amanhã</span></p>'
    expect(stripHtml(input)).toBe('Ação pendente até amanhã')
  })
})
