import LZString from 'lz-string'
import { afterEach, describe, expect, it } from 'vitest'
import type { MeetingMinutesStorage } from '@/types'
import { encodeAtaToHash, parseAtaFromHash } from './urlAtaImport'

const BASE_STORAGE: MeetingMinutesStorage = {
  cabecalho: {
    numero: '123',
    data: '2026-03-14',
    tipo: 'Ordinaria',
    titulo: 'Ata de teste',
    responsavel: 'Joao',
    projeto: 'Projeto X',
    contrato: 'CTR-001',
  },
  attendance: [
    {
      nome: 'Maria',
      email: 'maria@example.com',
      empresa: 'Vale',
      telefone: '11999999999',
      presenca: 'P',
    },
  ],
  itens: [
    {
      id: 'item-1',
      item: '1',
      nivel: 1,
      pai: null,
      filhos: [],
      criadoEm: '2026-03-14T10:00:00.000Z',
      historico: [
        {
          id: 'hist-1',
          criadoEm: '2026-03-14T10:00:00.000Z',
          descricao: 'Descricao inicial',
          responsavel: { nome: 'Maria', email: 'maria@example.com' },
          data: '2026-03-20',
          status: 'Pendente',
        },
      ],
      UltimoHistorico: {
        id: 'hist-1',
        criadoEm: '2026-03-14T10:00:00.000Z',
        descricao: 'Descricao inicial',
        responsavel: { nome: 'Maria', email: 'maria@example.com' },
        data: '2026-03-20',
        status: 'Pendente',
      },
    },
  ],
}

function utf8ToBase64(value: string): string {
  const bytes = new TextEncoder().encode(value)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

afterEach(() => {
  window.location.hash = ''
})

describe('parseAtaFromHash', () => {
  it('returns null when hash is empty', () => {
    window.location.hash = ''
    expect(parseAtaFromHash()).toBeNull()
  })

  it('parses legacy base64 hash payload', () => {
    window.location.hash = `#${utf8ToBase64(JSON.stringify(BASE_STORAGE))}`
    expect(parseAtaFromHash()).toEqual(BASE_STORAGE)
  })

  it('parses compressed hash generated by encodeAtaToHash', () => {
    window.location.hash = `#${encodeAtaToHash(BASE_STORAGE)}`
    expect(parseAtaFromHash()).toEqual(BASE_STORAGE)
  })

  it('parses minimal payload and expands historico', () => {
    const minimalPayload = {
      c: BASE_STORAGE.cabecalho,
      a: BASE_STORAGE.attendance,
      i: [
        {
          id: 'item-min',
          item: '1',
          nivel: 1,
          pai: null,
          filhos: [],
          criadoEm: '2026-03-14T11:00:00.000Z',
          u: {
            id: 'hist-min',
            criadoEm: '2026-03-14T11:00:00.000Z',
            descricao: 'Acao minima',
            responsavel: { nome: 'Maria', email: 'maria@example.com' },
            data: null,
            status: 'Concluído',
          },
        },
      ],
    }
    window.location.hash = `#m${LZString.compressToBase64(JSON.stringify(minimalPayload))}`

    const parsed = parseAtaFromHash()
    expect(parsed).not.toBeNull()
    expect(parsed?.itens).toHaveLength(1)
    expect(parsed?.itens[0]?.historico).toHaveLength(1)
    expect(parsed?.itens[0]?.UltimoHistorico.status).toBe('Concluído')
    expect(parsed?.itens[0]?.historico[0]).toEqual(parsed?.itens[0]?.UltimoHistorico)
  })

  it('returns null when decoded payload is invalid structure', () => {
    window.location.hash = `#z${LZString.compressToBase64(JSON.stringify({ foo: 'bar' }))}`
    expect(parseAtaFromHash()).toBeNull()
  })
})
