import { afterEach, describe, expect, it } from 'vitest'
import LZString from 'lz-string'
import { encodeAtaToHash, parseAtaFromHash } from './urlAtaImport'

function utf8ToBase64(value: string): string {
  const bytes = new TextEncoder().encode(value)
  let binary = ''
  for (const byte of bytes) {
    binary += String.fromCharCode(byte)
  }
  return btoa(binary)
}

describe('urlAtaImport', () => {
  afterEach(() => {
    window.location.hash = ''
  })

  it('parses compressed hash generated by encodeAtaToHash', () => {
    const meetingMinutes = {
      id: 'ata-1',
      cabecalho: {
        numero: 'ATA-001',
        data: '2026-04-08',
        tipo: 'Ordinária',
        titulo: 'Reunião de Planejamento',
        responsavel: 'Maria Silva',
        projeto: 'Projeto X',
        contrato: 'CTR-123',
      },
      attendance: [{ nome: 'Ana', email: 'ana@empresa.com', empresa: 'Vale', telefone: '1111', presenca: 'P' as const }],
      itens: [],
      createdAt: '2026-04-08T10:00:00.000Z',
      updatedAt: '2026-04-08T10:00:00.000Z',
    }

    const hash = encodeAtaToHash(meetingMinutes)
    window.location.hash = `#${hash}`

    expect(parseAtaFromHash()).toEqual({
      cabecalho: meetingMinutes.cabecalho,
      attendance: meetingMinutes.attendance,
      itens: meetingMinutes.itens,
    })
  })

  it('parses minimal compressed payload and expands defaults', () => {
    const lastHistory = {
      id: 'hist-1',
      criadoEm: '2026-04-08T10:00:00.000Z',
      descricao: 'Ação criada',
      responsavel: { nome: 'Ana', email: 'ana@empresa.com' },
      data: '2026-04-10',
      status: 'Pendente',
    }
    const minimal = {
      c: {
        numero: 'ATA-010',
        data: '2026-04-08',
        tipo: 'Ordinária',
        titulo: 'Ata minimal',
        responsavel: 'Ana',
        projeto: 'Projeto Y',
      },
      a: [{ nome: 'Ana', email: 'ana@empresa.com', empresa: 'Vale', telefone: '1111', presenca: 'P' }],
      i: [
        {
          id: 'item-1',
          item: '1',
          nivel: 1,
          criadoEm: '2026-04-08T10:00:00.000Z',
          u: lastHistory,
        },
      ],
    }

    window.location.hash = `#m${LZString.compressToBase64(JSON.stringify(minimal))}`

    expect(parseAtaFromHash()).toEqual({
      cabecalho: minimal.c,
      attendance: minimal.a,
      itens: [
        {
          id: 'item-1',
          item: '1',
          nivel: 1,
          pai: null,
          filhos: [],
          criadoEm: '2026-04-08T10:00:00.000Z',
          historico: [lastHistory],
          UltimoHistorico: lastHistory,
        },
      ],
    })
  })

  it('parses legacy plain base64 hash with UTF-8 payload', () => {
    const payload = {
      cabecalho: {
        numero: 'ATA-UTF8',
        data: '2026-04-08',
        tipo: 'Ordinária',
        titulo: 'Reunião com ação',
        responsavel: 'José',
        projeto: 'Operação São Luís',
      },
      attendance: [],
      itens: [],
    }
    const json = JSON.stringify(payload)
    window.location.hash = `#${utf8ToBase64(json)}`

    expect(parseAtaFromHash()).toEqual(payload)
  })

  it('returns null for malformed or invalid payloads', () => {
    window.location.hash = '#znot-valid-base64'
    expect(parseAtaFromHash()).toBeNull()

    const invalid = { cabecalho: {}, attendance: {} }
    window.location.hash = `#${utf8ToBase64(JSON.stringify(invalid))}`
    expect(parseAtaFromHash()).toBeNull()
  })
})
