import LZString from 'lz-string'
import { afterEach, describe, expect, it } from 'vitest'
import type { MeetingMinutesStorage } from '@/types'
import { encodeAtaToHash, parseAtaFromHash } from './urlAtaImport'

function createStorageFixture(): MeetingMinutesStorage {
  return {
    cabecalho: {
      numero: 'ATA-001',
      data: '2026-03-20',
      tipo: 'Ordinaria',
      titulo: 'Reuniao Semanal',
      responsavel: 'Ana',
      projeto: 'Projeto A',
      contrato: 'CTR-1',
    },
    attendance: [
      {
        nome: 'Ana',
        email: 'ana@example.com',
        empresa: 'Vale',
        telefone: '11999999999',
        presenca: 'P',
      },
    ],
    itens: [
      {
        id: 'item-1',
        item: '1',
        nivel: 1,
        pai: null,
        filhos: [],
        criadoEm: '2026-03-20T10:00:00.000Z',
        historico: [
          {
            id: 'hist-1',
            criadoEm: '2026-03-20T10:00:00.000Z',
            descricao: 'Descricao inicial',
            responsavel: { nome: 'Ana', email: 'ana@example.com' },
            data: '2026-03-21',
            status: 'Pendente',
          },
        ],
        UltimoHistorico: {
          id: 'hist-1',
          criadoEm: '2026-03-20T10:00:00.000Z',
          descricao: 'Descricao inicial',
          responsavel: { nome: 'Ana', email: 'ana@example.com' },
          data: '2026-03-21',
          status: 'Pendente',
        },
      },
    ],
  }
}

describe('parseAtaFromHash', () => {
  afterEach(() => {
    window.location.hash = ''
  })

  it('parses legacy base64 hash payload', () => {
    const storage = createStorageFixture()
    const encoded = btoa(JSON.stringify(storage))
    window.location.hash = `#${encoded}`

    const parsed = parseAtaFromHash()

    expect(parsed).toEqual(storage)
  })

  it('parses compressed hash payload generated by encodeAtaToHash', () => {
    const storage = createStorageFixture()
    window.location.hash = `#${encodeAtaToHash(storage)}`

    const parsed = parseAtaFromHash()

    expect(parsed).toEqual(storage)
  })

  it('expands minimal format with default history when UltimoHistorico is absent', () => {
    const storage = createStorageFixture()
    const minimalPayload = {
      c: storage.cabecalho,
      a: storage.attendance,
      i: [
        {
          id: 'item-min',
          item: '1',
          nivel: 1,
          criadoEm: '2026-03-20T10:00:00.000Z',
          filhos: [],
        },
      ],
    }
    window.location.hash = `#m${LZString.compressToBase64(JSON.stringify(minimalPayload))}`

    const parsed = parseAtaFromHash()

    expect(parsed).not.toBeNull()
    expect(parsed?.itens[0]?.UltimoHistorico.status).toBe('Pendente')
    expect(parsed?.itens[0]?.historico).toHaveLength(1)
    expect(parsed?.itens[0]?.UltimoHistorico.responsavel).toEqual({ nome: '', email: '' })
  })

  it('returns null for malformed compressed payload', () => {
    window.location.hash = '#znot-a-valid-payload'

    const parsed = parseAtaFromHash()

    expect(parsed).toBeNull()
  })
})
